### PR TITLE
Fix/ipv6

### PR DESCRIPTION
**Pull request by thibaultcha**

### CODE REVIEW

**Comment by phpb-com** [comment]
Thanks for bringing this PR to a live branch of this project. I am happy to help with the test cases if needed or amend this change.

**Comment by thibaultcha** [comment]
Hi,

I've been working on an improved for of the original project [here](http://github.com/thibaultCha/lua-cassandra) with many improvements and the fix you provided. Test cases for it would be very welcomed

**Comment by phpb-com** [comment]
@thibaultCha will do, let me see if I can provide a fresh PR with above changes and test cases.

**Comment by phpb-com** [comment]
@thibaultCha perhaps you want to close this PR and use #2 as the main one, I've added test cases to this one.

**Pull request closed without merging**
